import { escapeRegExp } from "./escapeRegExp.js";

let _emoticons = [
  { img: "brb.gif", key: "Be Right Back", text: "(brb)" },
  { img: "sunshine.webp", key: "Sunshine", text: "(#)" },
  { img: "74_74.gif", key: "Party", text: "&lt;:o)" },
  { img: "dog.gif", key: "Dog face", text: "(&amp;)" },
  { img: "rainbow.webp", key: "Rainbow", text: "(R)" },
  { img: "regular_smile.gif", key: "Smile", text: [":-)", ":)"] },
  { img: "teeth_smile.gif", key: "Open-mouthed", text: [":-D", ":d"] },
  { img: "omg_smile.gif", key: "Surprised", text: [":-O", ":o"] },
  { img: "tongue_smile.gif", key: "Tongue out", text: [":-P", ":p"] },
  { img: "wink_smile.gif", key: "Wink", text: [";-)", ";)"] },
  { img: "sad_smile.gif", key: "Sad", text: [":-(", ":("] },
  { img: "confused_smile.gif", key: "Confused", text: [":-S", ":s"] },
  { img: "what_smile.gif", key: "Disappointed", text: [":-|", ":|"] },
  { img: "cry_smile.gif", key: "Crying", text: ":'(" },
  { img: "red_smile.gif", key: "Embarrassed", text: [":-$", ":$"] },
  { img: "shades_smile.gif", key: "Hot", text: "(H)" },
  { img: "angry_smile.gif", key: "Angry", text: [":-@", ":@"] },
  { img: "angel_smile.gif", key: "Angel", text: "(A)" },
  { img: "devil_smile.gif", key: "Devil", text: "(6)" },
  { img: "47_47.gif", key: "Don't tell anyone", text: ":-#" },
  { img: "48_48.gif", key: "Baring teeth", text: "8o|" },
  { img: "49_49.gif", key: "Nerd", text: "8-|" },
  { img: "50_50.gif", key: "Sarcastic", text: "^o)" },
  { img: "51_51.gif", key: "Secret telling", text: ":-*" },
  { img: "52_52.gif", key: "Sick", text: "+o(" },
  { img: "71_71.gif", key: "I don't know", text: ":^)" },
  { img: "72_72.gif", key: "Thinking", text: "*-)" },
  { img: "75_75.gif", key: "Eye-rolling", text: "8-)" },
  { img: "77_77.gif", key: "Sleepy", text: "|-)" },
  { img: "coffee.gif", key: "Coffee cup", text: "(C)" },
  { img: "thumbs_up.gif", key: "Thumbs up", text: "(Y)" },
  { img: "thumbs_down.gif", key: "Thumbs down", text: "(N)" },
  { img: "beer_mug.gif", key: "Beer mug", text: "(B)" },
  { img: "martini.gif", key: "Martini glass", text: "(D)" },
  { img: "girl.gif", key: "Girl", text: "(X)" },
  { img: "guy.gif", key: "Boy", text: "(Z)" },
  { img: "guy_hug.gif", key: "Left hug", text: "({)" },
  { img: "girl_hug.gif", key: "Right hug", text: "(})" },
  { img: "bat.gif", key: "Vampire bat", text: [":-[", ":["] },
  { img: "cake.gif", key: "Birthday cake", text: "(^)" },
  { img: "heart.gif", key: "Red heart", text: "(L)" },
  { img: "broken_heart.gif", key: "Broken heart", text: "(U)" },
  { img: "kiss.gif", key: "Red lips", text: "(K)" },
  { img: "present.gif", key: "Gift with a bow", text: "(G)" },
  { img: "rose.gif", key: "Red rose", text: "(F)" },
  { img: "wilted_rose.gif", key: "Wilted rose", text: "(W)" },
  { img: "camera.gif", key: "Camera", text: "(P)" },
  { img: "film.gif", key: "Filmstrip", text: "(~)" },
  { img: "cat.gif", key: "Cat face", text: "(@)" },
  { img: "phone.gif", key: "Telephone receiver", text: "(T)" },
  { img: "lightbulb.gif", key: "Light bulb", text: "(I)" },
  { img: "note.gif", key: "Note", text: "(8)" },
  { img: "moon.gif", key: "Sleeping half-moon", text: "(S)" },
  { img: "star.gif", key: "Star", text: "(*)" },
  { img: "envelope.gif", key: "E-mail", text: "(E)" },
  { img: "clock.gif", key: "Clock", text: "(O)" },
  { img: "messenger.gif", key: "MSN Messenger icon", text: "(M)" },
  { img: "53_53.gif", key: "Snail", text: "(sn)" },
  { img: "70_70.gif", key: "Black Sheep", text: "(bah)" },
  { img: "55_55.gif", key: "Plate", text: "(pl)" },
  { img: "56_56.gif", key: "Bowl", text: "(||)" },
  { img: "57_57.gif", key: "Pizza", text: "(pi)" },
  { img: "58_58.gif", key: "Soccer ball", text: "(so)" },
  { img: "59_59.gif", key: "Auto", text: "(au)" },
  { img: "60_60.gif", key: "Airplane", text: "(ap)" },
  { img: "61_61.gif", key: "Umbrella", text: "(um)" },
  { img: "62_62.gif", key: "Island with a palm tree", text: "(ip)" },
  { img: "63_63.gif", key: "Computer", text: "(co)" },
  { img: "64_64.gif", key: "Mobile Phone", text: "(mp)" },
  { img: "66_66.gif", key: "Stormy cloud", text: "(st)" },
  { img: "73_73.gif", key: "Lightning", text: "(li)" },
  { img: "69_69.gif", key: "Money", text: "(mo)" },
];

const emoticons = _emoticons.map((emoticon) => ({
  ...emoticon,
  // Add regex
  regex: (Array.isArray(emoticon.text) ? emoticon.text : [emoticon.text]).map(
    (text) => new RegExp(escapeRegExp(text), "ig")
  ),
  // Change img to include prefix
  img: `images/emoticons/${emoticon.img}`,
}));

export { emoticons };

